name: Generate changelog

on:
  release:
    types: [created, edited]
  push:
    branches: [main]
jobs:
  run_tests:
    permissions: write-all
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for Tag
      run: |
        TAG="0.0.1"
        if [ $(git tag -l "${TAG}") ]; then
          echo "Tag ${TAG} exists"
        else
          echo "Tag ${TAG} does not exist"
        fi

    
    # - name: Clone repository
    #   run: |
    #     git clone https://github.com/leoviana00/config-repo-base-autochangelog.git
    #     git config user.name "CI Pipeline"
    #     git config user.email "cipipeline@example.com" 
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Run script file
    #   run: |
    #     chmod +x changelog.sh
    #     ./changelog.sh
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment Changelog on Success and Add Label 
      if: success()
      run: |
        cat <<EOT > message.txt
        Ol√°! Changelog atualizado com sucesso ü•≥üöÄ
        EOT

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment Changelog on Failure
      if: failure()
      run: |
        cat <<EOT > message.txt
        Ol√°! üö´ Parece que houve um problema a atualiza√ß√£o do changelog üßê Aqui est√£o algumas coisas para verificar:

        - Verificar token de acesso.
        - Checar se n√£o hove nenhuma mudan√ßa nas configura√ß√µes nos √∫timos dias.

        Agradecemos sua contribui√ß√£o e compreens√£o üëäüòâ
        EOT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}