name: Generate changelog

on:
  release:
    types: [created, edited]
  push:
    branches: [main]
jobs:
  run_tests:
    permissions: write-all
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
    
    - name: Clone repository
      run: |
        git clone https://github.com/leoviana00/config-repo-base-autochangelog.git
        git config user.name "CI Pipeline"
        git config user.email "cipipeline@example.com" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run script file
      run: |
        version=$(cat version.json | grep version | grep -Eo "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")

        for THIS_TAG in "$version"; do

            git tag -l "$THIS_TAG" | tac

            if [ $(git tag -l "$THIS_TAG") ]; then
                echo "Tag $THIS_TAG jÃ¡ existe. Adicionando alteraÃ§Ãµes no CHANGELOG.md ..."
                chmod +x note-releases.sh
                ./note-releases.sh > CHANGELOG.md
                git add CHANGELOG.md 
                git commit -m "docs(CHANGELOG): update release notes"
                git push origin HEAD:main
            else
                echo "Tag $THIS_TAG nÃ£o existe. Criando tag e adicionando notas de alteraÃ§Ãµes no CHANGELOG.md ..."
                git tag "$THIS_TAG"
                git push  --tags https://github.com/leoviana00/config-repo-base-autochangelog.git HEAD:main
                chmod +x note-releases.sh
                ./note-releases.sh > CHANGELOG.md
                git add CHANGELOG.md 
                git commit -m "docs(CHANGELOG): update release notes"
                git push origin HEAD:main
            fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment Changelog on Success and Add Label 
      if: success()
      run: |
        cat <<EOT > message.txt
        OlÃ¡! Changelog atualizado com sucesso ğŸ¥³ğŸš€
        EOT

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment Changelog on Failure
      if: failure()
      run: |
        cat <<EOT > message.txt
        OlÃ¡! ğŸš« Parece que houve um problema a atualizaÃ§Ã£o do changelog ğŸ§ Aqui estÃ£o algumas coisas para verificar:

        - Verificar token de acesso.
        - Checar se nÃ£o hove nenhuma mudanÃ§a nas configuraÃ§Ãµes nos Ãºtimos dias.

        Agradecemos sua contribuiÃ§Ã£o e compreensÃ£o ğŸ‘ŠğŸ˜‰
        EOT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}