name: Generate changelog

on:
  release:
    types: [created, edited]
  push:
    branches: [main]
jobs:
  run_tests:
    permissions: write-all
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
    
    - name: Clone repository
      run: |
        git clone https://github.com/leoviana00/config-repo-base-autochangelog.git
        git config user.name "CI Pipeline"
        git config user.email "cipipeline@example.com" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run script file
      run: |
        chmod +x changelog.sh
        ./changelog.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment Changelog on Success and Add Label 
      if: success()
      run: |
        cat <<EOT > message.txt
        OlÃ¡! Changelog atualizado com sucesso ğŸ¥³ğŸš€
        EOT

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment Changelog on Failure
      if: failure()
      run: |
        cat <<EOT > message.txt
        OlÃ¡! ğŸš« Parece que houve um problema a atualizaÃ§Ã£o do changelog ğŸ§ Aqui estÃ£o algumas coisas para verificar:

        - Verificar token de acesso.
        - Checar se nÃ£o hove nenhuma mudanÃ§a nas configuraÃ§Ãµes nos Ãºtimos dias.

        Agradecemos sua contribuiÃ§Ã£o e compreensÃ£o ğŸ‘ŠğŸ˜‰
        EOT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}